---

- name: Install postgresql
  pkgng:
    # default php56-pgsql depends on 9.3
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql95-server
    - postgresql95-client
    - py27-psycopg2
